const text = {
  FAILED_CONNECT_REDIS: 'FAILED_CONNECT_REDIS',
  FAILED_GET_ERR: 'FAILED_GER_ERR',
  OK_CONNECT_REDIS: 'OK_CONNECT_REDIS',
  FAILED_RESET: 'FAILED_RESET_IN_PROCESSING',
  SUBSCRIBED_TO_CHANNEL: 'SUBSCRIBED_TO_CHANNEL:',
  RECIEVED_MESSAGE_FROM_CHANNEL: 'RECIEVED_MESSAGE_FROM_CHANNEL:',
  RECIEVED_ERR_MESSAGE_FROM_CHANNEL: 'RECIEVED_ERR_MESSAGE_FROM_CHANNEL:',
  MESSAGE_PROCESSED: 'MESSAGE_PROCESSED',
  MESSAGE_PUBLISHED: 'MESSAGE_PUBLISHED',
  PUB_MESSAGE_PUBLISHED: 'PUB_MESSAGE_PUBLISHED',
  NO_PUB_MESSAGE_PUBLISHED: 'NO_PUB_MESSAGE_PUBLISHED',
  DELETE_MESSAGE_FROM_REDIS: 'DELETE_MESSAGE_FROM_REDIS',
  OPEN_CHANNEL: 'OPEN_CHANNEL',
  CLOSE_CHANNEL: 'CLOSE_CHANNEL',
  UNSUBSCRIBE: 'UNSUBSCRIBE',
  UNHANDLED_REJECTION_ERR: 'UNHANDLED_REJECTION_ERR'
};

const GET_ERR_FLAG = '--getErrors';

const REDIS_EXPIRE_SEC = 1000;

const MESSAGE_INTERVAL = 500;

const CHECK_INTERVAL = 500;

const MAX_RANDOM_STRING_LENGTH = 100;

const CHANNEL_NAME = 'MessageChannel';

const MESSAGE_LIST = 'MessageList';

const MESSAGE_TYPE = 'msg';

const PUB_MESSAGE_TYPE = 'pub';

const NO_PUB_MESSAGE_TYPE = 'nopub';

module.exports = {
  text,
  CHANNEL_NAME,
  MESSAGE_LIST,
  MESSAGE_TYPE,
  PUB_MESSAGE_TYPE,
  NO_PUB_MESSAGE_TYPE,
  MESSAGE_INTERVAL,
  CHECK_INTERVAL,
  REDIS_EXPIRE_SEC,
  GET_ERR_FLAG,
  MAX_RANDOM_STRING_LENGTH
};
